run:
  timeout: 5m
  tests: true

linters:
  enable:
    - govet
    - staticcheck
    - gofmt
    - goimports
    - unused
    - depguard
    - errcheck
    - revive

issues:
  exclude-files:
    - ".*\\.gen\\.go$"
    - ".*_mock\\.go$"
  exclude-dirs:
    - "infra/mock"
    - "logs"
    - "cmd/http"

output:
  format: colored-line-number
  max-issues-per-linter: 0
  max-same-issues: 0
