run:
  timeout: 5m
  tests: true

linters:
  enable:
    - govet
    - staticcheck
    - gofmt
    - goimports
    - unused
    - depguard
    - errcheck
    - revive

linters-settings:
  depguard:
    rules:
      handler:
        deny:
          - pkg: github.com/WagaoCarvalho/backend_store_go/internal/repo
            desc: "Handler não deve acessar Repository direto, só via Service"
          - pkg: github.com/WagaoCarvalho/backend_store_go/internal/model
            desc: "Handler não deve depender de Models"
          - pkg: github.com/jackc/pgx/v5
            desc: "Handler não deve acessar DB"
        allow:
          # stdlib
          - "^[a-z]+$"
          - bytes
          - context
          - errors
          - fmt
          - io
          - log
          - net/http
          - os
          - regexp
          - strconv
          - strings
          - sync
          - testing
          - time
          - unicode

          # terceiros
          - github.com/stretchr/testify/assert
          - github.com/stretchr/testify/mock
          - github.com/joho/godotenv
          - github.com/sirupsen/logrus
          - github.com/redis/go-redis/v9
          - gopkg.in/natefinch/lumberjack.v2
          - golang.org/x/time/rate
          - golang.org/x/crypto/bcrypt
          - github.com/jackc/pgx/v5/pgxpool
          - github.com/jackc/pgx/v5
          - github.com/jackc/pgx/v5/pgconn  # necessário por import transitivo

          # internos
          - github.com/WagaoCarvalho/backend_store_go/config
          - github.com/WagaoCarvalho/backend_store_go/internal/pkg/logger
          - github.com/WagaoCarvalho/backend_store_go/internal/pkg/utils
          - github.com/WagaoCarvalho/backend_store_go/internal/pkg/middleware/context_utils
          - github.com/WagaoCarvalho/backend_store_go/internal/pkg/err/db
          - github.com/WagaoCarvalho/backend_store_go/internal/pkg/err/message

          - github.com/WagaoCarvalho/backend_store_go/internal/model/address
          - github.com/WagaoCarvalho/backend_store_go/internal/model/contact
          - github.com/WagaoCarvalho/backend_store_go/internal/model/user
          - github.com/WagaoCarvalho/backend_store_go/internal/model/user/user_categories
          - github.com/WagaoCarvalho/backend_store_go/internal/model/user/user_category_relations

          - github.com/WagaoCarvalho/backend_store_go/internal/repo/user/user_categories
          - github.com/WagaoCarvalho/backend_store_go/infra/mock/repo/user

          - github.com/WagaoCarvalho/backend_store_go/internal/service

      service:
        deny:
          - pkg: github.com/WagaoCarvalho/backend_store_go/internal/handler
            desc: "Service não deve depender de Handler"
        allow:
          - "^[a-z]+$"
          - context
          - errors
          - fmt
          - regexp
          - strings
          - testing
          - time
          - github.com/WagaoCarvalho/backend_store_go/internal/repo
          - github.com/WagaoCarvalho/backend_store_go/internal/model
          - github.com/WagaoCarvalho/backend_store_go/internal/pkg/logger
          - github.com/WagaoCarvalho/backend_store_go/internal/pkg/err

      repository:
        deny:
          - pkg: github.com/WagaoCarvalho/backend_store_go/internal/handler
            desc: "Repository não deve depender de Handler"
          - pkg: github.com/WagaoCarvalho/backend_store_go/internal/service
            desc: "Repository não deve depender de Service"
        allow:
          - "^[a-z]+$"
          - context
          - errors
          - fmt
          - regexp
          - strings
          - testing
          - time
          - github.com/jackc/pgx/v5
          - github.com/jackc/pgx/v5/pgxpool
          - github.com/WagaoCarvalho/backend_store_go/internal/model
          - github.com/WagaoCarvalho/backend_store_go/internal/pkg/logger
          - github.com/WagaoCarvalho/backend_store_go/internal/pkg/err
          - github.com/WagaoCarvalho/backend_store_go/internal/pkg/utils/validators/validator

      pkg:
        allow:
          - "^[a-z]+$"
          - context
          - errors
          - fmt
          - io
          - log
          - net/http
          - net/http/httptest
          - os
          - regexp
          - strings
          - strconv
          - testing
          - time

          # terceiros
          - github.com/joho/godotenv
          - github.com/redis/go-redis/v9
          - github.com/sirupsen/logrus
          - github.com/stretchr/testify/mock
          - github.com/stretchr/testify/assert
          - gopkg.in/natefinch/lumberjack.v2

          # internos
          - github.com/WagaoCarvalho/backend_store_go/internal/pkg/...
          - github.com/WagaoCarvalho/backend_store_go/internal/pkg/logger
          - github.com/WagaoCarvalho/backend_store_go/internal/pkg/err/message
          - github.com/WagaoCarvalho/backend_store_go/internal/pkg/middleware/context_utils
          - github.com/WagaoCarvalho/backend_store_go/internal/pkg/utils/validators/address
          - github.com/WagaoCarvalho/backend_store_go/internal/pkg/utils/validators/contact
          - github.com/WagaoCarvalho/backend_store_go/internal/pkg/utils/validators/validator
