name: Run Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_pass
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U test_user"
          --health-interval 5s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout código-fonte
        uses: actions/checkout@v4

      - name: Instalar Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21

      - name: Configurar ambiente
        run: |
          echo "DATABASE_URL=postgres://test_user:test_pass@localhost:5432/test_db?sslmode=disable" > .env

      - name: Baixar dependências
        run: go mod download

      - name: Aguardar PostgreSQL ficar pronto
        run: |
          for i in {1..10}; do
            pg_isready -h localhost -p 5432 -U test_user && exit 0
            echo "Aguardando PostgreSQL..."
            sleep 2
          done
          echo "PostgreSQL não respondeu a tempo." && exit 1

      - name: Executar testes
        env:
          DATABASE_URL: postgres://test_user:test_pass@localhost:5432/test_db?sslmode=disable
        run: go test ./...
